# Generated by Django 4.1.1 on 2022-09-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=20)),
                ('doc_phon', models.IntegerField(verbose_name=10)),
                ('doc_add', models.CharField(max_length=100)),
            ],
        ),
    ]
