# Generated by Django 4.1.1 on 2022-09-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_name', models.CharField(max_length=20)),
                ('use_phon', models.IntegerField(max_length=10)),
                ('use_add', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doc_phon',
            field=models.IntegerField(max_length=10),
        ),
    ]
