# Generated by Django 4.1.1 on 2022-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_user_alter_doctor_doc_phon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_phon',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='use_phon',
            field=models.IntegerField(),
        ),
    ]
